# This is the Docker Compose entry point for this project.
# Services listed in this file will automatically be built and started when you bring
# the project up.
version: "3.7"
services:
  frontend:
    build:
      context: ./services/frontend
    environment:
      # Force polling instead of watching to work around Docker osxfs issues.
      CHOKIDAR_USEPOLLING: '1'
      CHOKIDAR_INTERVAL: '1000'
    ports:
      - 3000:3000
    volumes:
      - ./services/frontend/components:/app/components:cached
      - ./services/frontend/pages:/app/pages:cached
      - ./services/frontend/public:/app/public:cached
      - ./services/frontend/styles:/app/styles:cached
  
  database:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgres/data
    restart: always
    networks:
      default:
        aliases:
          - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  parse:
    build: ./services/parse
    depends_on:
      - database
    ports:
      - 9229:9229 # node debugger
      - 3001:3001
    command: ['node', '--inspect=0.0.0.0:9229', 'lib/index.js']
    environment:
      NODE_ENV: development
      PARSE_DATABASE_URL: 'postgres://postgres:password@database:5432/postgres'
      PARSE_APP_ID: poc
      PARSE_MASTER_KEY: pocmaster
      PARSE_CLIENT_ID: test
      PARSE_SERVER_URL: http://localhost:3001/parse
    networks:
      default:
        aliases:
          - parse-server

  dashboard:
    image: 'parseplatform/parse-dashboard'
    depends_on: 
      - parse
    ports:
      - 4040:4040
    environment:
      HOST: '0.0.0.0'
      PORT: '4040'
      MOUNT_PATH: /
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 'true'
      PARSE_DASHBOARD_CONFIG: >
        {
          "apps": [
            {
              "appId": "poc",
              "masterKey": "pocmaster",
              "appName": "Local Parse",
              "serverURL": "http://localhost:3001/parse"
            }
          ],
          "users": [
            {
              "user": "local",
              "pass": "local"
            }
          ]
        }

volumes:
  pgdata:
  fsdata:
